### ISSUE TITLE
Roadmap 0.1.x

### ISSUE THREAD

**Issue by vankop** [vankop/glyph-size-loader#1]
- [ ] Provide README with issue example that loader solves
- [ ] Support more char ranges, may be support language codes, e.g. `ru-RU`
- [ ] Support ligatures
- [ ] enhance complex example (code snippets, describe motivation of use)
- [ ] CI-CD
